/* eslint-disable @typescript-eslint/no-unsafe-assignment */

import Hero from "@task/components/home/hero";
import InputModule from "@task/components/home/inputModule";
import Footer from "@task/components/shared/footer";
import Navbar from "@task/components/shared/navbar";
import { type ResponseInterface } from "@task/utils/schema";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [content, setContent] = useState<ResponseInterface | null>(null);
  return (
    <>
      <Head>
        <title>Tag It !</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col justify-between">
        <Navbar />
        <div className="flex h-full justify-evenly">
          {content !== null && content !== undefined ? (
            <InputModule content={content} setContent={setContent} />
          ) : (
            <>
              <Hero />
              <InputModule content={content} setContent={setContent} />
            </>
          )}
        </div>
        <Footer />
      </main>
    </>
  );
}
